# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d1b3b7b5513b33ab7769a60a7bdd4c52"
name = "fop-report"
handle = "fop-report"
application_url = "https://craig-asked-played-substantial.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,write_orders"

[auth]
redirect_urls = [
  "https://craig-asked-played-substantial.trycloudflare.com/auth/callback",
  "https://craig-asked-played-substantial.trycloudflare.com/auth/shopify/callback",
  "https://craig-asked-played-substantial.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
